version: "3.9"
services:
  backend:
    labels:
      - traefik.enable=true
    networks:
      default:
        aliases:
          - yaltt-backend
    environment:
      - YALTT_HOST=yaltt.inst.test

  frontend:
    labels:
      - traefik.enable=true
      - "traefik.http.routers.frontend.rule=Host(`yaltt.inst.test`)"
    networks:
      default:
        aliases:
          - yaltt.inst.test
  db:
    networks:
      default:
        aliases:
          - yaltt-db

networks:
  default:
    external: true
    name: "inst_shared"